# https://www.prisma.io/docs/orm/prisma-client/testing/integration-testing
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:16
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
